//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KM
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLOYEE
    {
        public string ID { get; set; }
        public string FULL_NAME { get; set; }
        public string ROLES { get; set; }
    }
}
