//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KM
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROJECT
    {
        public string ID { get; set; }
        public string P1_NAME { get; set; }
        public string P1_SKILL { get; set; }
        public string P1_LEVEL { get; set; }
        public string P2_NAME { get; set; }
        public string P2_SKILL { get; set; }
        public string P2_LEVEL { get; set; }
        public string P3_NAME { get; set; }
        public string P3_SKILL { get; set; }
        public string P3_LEVEL { get; set; }
    }
}
