//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KM
{
    using System;
    using System.Collections.Generic;
    
    public partial class SKL5
    {
        public string ID { get; set; }
        public string SKILL1 { get; set; }
        public string LEVEL1 { get; set; }
        public string SKILL2 { get; set; }
        public string LEVEL2 { get; set; }
        public string SKILL3 { get; set; }
        public string LEVEL3 { get; set; }
    }
}
