CREATE TABLE PROJECT(
ID INT NOT NULL,
P1_NAME VARCHAR(20) NOT NULL,
P1_SKILL VARCHAR(20) NOT NULL,
P1_LEVEL VARCHAR(20) NOT NULL,
P2_NAME VARCHAR(20) NOT NULL,
P2_SKILL VARCHAR(20) NOT NULL,
P2_LEVEL VARCHAR(20) NOT NULL,
P3_NAME VARCHAR(20) NOT NULL,
P3_SKILL VARCHAR(20) NOT NULL,
P3_LEVEL VARCHAR(20) NOT NULL);